# -*- coding: utf-8 -*-
"""Product_Behaviour_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJ5ewGRpG_EOl9ix2e4QnRo7iIXxfH44
"""

import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

# Download latest version
path = kagglehub.dataset_download("nalisha/shopping-behaviour-and-product-ranking-dateset")

print("Path to dataset files:", path)

df = pd.read_csv(f"{path}/shopping_behavior_updated (1).csv")

df

df.info()

df.isna().sum()

df.describe()

bins = [0, 18, 25, 35, 45, 60, 100]   # ranges
labels = ['0-18', '18-25', '25-35', '35-45', '45-60', '60+']
df['age_group'] = pd.cut(df['Age'],bins = bins,labels = labels)

"""🔹 A. Customer Behaviour Analysis"""

# What is the age distribution of customers? (histplot)

sns.histplot(df['Age'])
plt.title('Age distribution',fontweight = 'bold')
plt.xlabel('Age')
plt.ylabel('People')
plt.show()

# Compare Average Purchase Amount by Gender. (groupby + barplot)

avg_amount = df.groupby('Gender')['Purchase Amount (USD)'].mean()
plt.figure(figsize=(7,5))
plt.bar(avg_amount.index,avg_amount.values,color = ['#ff6e54','#003f5c'])
plt.title('Average Purchase Amount by Gender')
plt.xlabel('Gender')
plt.ylabel('Average purchase amount')

plt.show()

# Which age_group spends the most money?

most_money = df.groupby('age_group')['Purchase Amount (USD)'].sum()
plt.figure(figsize = (8,5))
plt.bar(most_money.index,most_money.values,color = 'teal',edgecolor = 'black')
plt.grid(axis='both', linestyle='--', alpha=0.4)
plt.title("Age group vs Money spend",fontweight = 'bold')
plt.xlabel('Age Group',fontweight = 'bold')
plt.ylabel('Purchase Amount',fontweight = 'bold')
for i, v in enumerate(most_money.values):
    plt.text(i, v + 50, str(v), ha='center', fontsize=10)
plt.show()

# Which Location has the highest total purchases?

high_purchase = df.groupby('Location')['Purchase Amount (USD)'].sum().sort_values(ascending = False).head(10)
plt.bar(high_purchase.index,high_purchase.values,color = 'dodgerblue',edgecolor = 'black')
for i, v in enumerate(high_purchase.values):
    plt.text(i, v + 50, str(v), ha='center', fontsize=10)
plt.title('Highest purchase by Location',fontweight = 'bold')
plt.xlabel('Location')
plt.xticks(rotation = 90)
plt.ylabel('Purchase Amount')
plt.show()

# What is the average Review Rating given by different age groups?

avg_rating = df.groupby('age_group')['Review Rating'].mean().round(2)
plt.bar(avg_rating.index,avg_rating.values,color = 'crimson',edgecolor = 'black')
plt.title('Avg review rating by age group',fontweight = 'bold')
plt.xlabel('Age group')
plt.ylabel('Average Rating')
for i , v in enumerate(avg_rating.values):
  plt.text(i,v+0.01,str(v),ha = 'center',fontsize = 10)

plt.show()

# Compare Frequency of Purchases for Male vs Female customers.

a = df.groupby(['Gender','Frequency of Purchases']).size()
a = a.reset_index(name = 'Count')
sns.barplot(x = a['Frequency of Purchases'] , y = a['Count'],hue = a['Gender'],edgecolor = 'black')
plt.title('Frequency of Purchases for Male vs Female customers',fontweight = 'bold')
plt.legend(loc = 'best')
plt.xticks(rotation = 90)
plt.tight_layout()
plt.show()

"""🔹 B. Product & Category Insights"""

# Which Item Purchased is the most popular? (countplot)

a = df.groupby(['Item Purchased','Review Rating']).size().sort_values(ascending = False).head(7)
a = a.reset_index(name = 'Count')

sns.barplot(data=a, y='Item Purchased', x='Count', hue='Review Rating')
plt.title('Most popular item purchased',fontweight = 'bold')
plt.xlabel('Number of Rating')
plt.tight_layout()
plt.show()

# Which Category generates the most revenue?

most_revenue = df.groupby('Category')['Purchase Amount (USD)'].sum()
plt.bar(most_revenue.index,most_revenue.values,color = 'teal',edgecolor = 'black')
plt.title('Revenue generates by category')
plt.xlabel('Category')
plt.ylabel('Purchase Amount (USD)')
for i , v in enumerate(most_revenue.values):
  plt.text(i,v+1000,str(v),ha = 'center',fontsize = 10)

plt.show()

# Identify the top 10 most revenue-generating items.

most_revenue_item = df.groupby('Item Purchased')['Purchase Amount (USD)'].sum().sort_values(ascending = False).head(10)
plt.bar(most_revenue_item.index,most_revenue_item.values,edgecolor = 'black')
plt.title('Top 10 most revenue-generating items',fontweight = 'bold')
plt.xlabel('Items')
plt.xticks(rotation = 90)
plt.ylabel('Purchased Amount in USD')
for i , v in enumerate(most_revenue_item):
  plt.text(i,v+100,str(v),ha = 'center')

plt.show()

# Does Size (S/M/L/XL) affect the Purchase Amount?

avg_price_size = df.groupby('Size')['Purchase Amount (USD)'].mean().round(2)
plt.bar(avg_price_size.index,avg_price_size.values,edgecolor = 'black')
plt.title('Size vs Purchase Amount',fontweight = 'bold')
plt.xlabel('Size')
plt.ylabel('Average purchase amount')
for i , v in enumerate(avg_price_size):
  plt.text(i,v+0.6,str(v),ha = 'center')
plt.show()

# Which Colors are purchased most frequently?

most_purchased = df['Color'].value_counts().sort_values(ascending=False).head(10)
plt.bar(most_purchased.index,most_purchased.values,color = 'plum',edgecolor = 'black')
plt.title('Most purchased by colors',fontweight = 'bold')
plt.xlabel('Colors')
plt.ylabel('Item purchased')
for i , v in enumerate(most_purchased.values):
  plt.text(i,v+1,str(v),ha = 'center')

plt.show()

# Compare Review Rating across different Categories.

avg_rating_category = df.groupby('Category')['Review Rating'].mean().round(2)
plt.bar(avg_rating_category.index,avg_rating_category.values,color = 'dodgerblue',edgecolor = 'black' )
plt.title('Review Rating across different Categories',fontweight = 'bold')
plt.xlabel('Categories')
plt.ylabel('Review Rating')
for i , v in enumerate(avg_rating_category):
  plt.text(i,v+0.05,str(v),ha = 'center')

plt.show()

# Analyze whether customers prefer different Colors in different Seasons. (heatmap or countplot with hue)

heat = pd.crosstab(df['Season'], df['Color'])
sns.heatmap(heat, annot=True, cmap='coolwarm',linewidths = 3)

plt.show()

"""C. Seasonal Trends"""

# Which Season has the highest total sales?

total_sales = df.groupby('Season')['Purchase Amount (USD)'].sum()
plt.bar(total_sales.index,total_sales.values,color = 'dodgerblue',edgecolor = 'black' )
plt.title('Highest total sales by season',fontweight = 'bold')
plt.xlabel('Season')
plt.ylabel('Purchased Amount')
for i , v in enumerate(total_sales.values):
  plt.text(i,v+100,str(v),ha = 'center')

plt.show()

# Plot average Purchase Amount vs Season.

avg_purchase = df.groupby('Season')['Purchase Amount (USD)'].mean().round(2)
plt.bar(avg_purchase.index,avg_purchase.values,color = 'dodgerblue',edgecolor = 'black' )
plt.title('Average Purchase Amount vs Season',fontweight = 'bold')
plt.xlabel('Season')
plt.ylabel('Avergae purchased Amount')
for i , v in enumerate(avg_purchase.values):
  plt.text(i,v+0.5,str(v),ha = 'center')

plt.show()

# Are Review Ratings higher or lower in any particular season?

avg_rating = df.groupby('Season')['Review Rating'].mean().round(2)
plt.bar(avg_rating.index,avg_rating.values,color = 'dodgerblue',edgecolor = 'black' )
plt.title('Average Review rating vs Season',fontweight = 'bold')
plt.xlabel('Season')
plt.ylabel('Avergae Review rating')
for i , v in enumerate(avg_rating.values):
  plt.text(i,v+0.05,str(v),ha = 'center')

plt.show()

# Which product categories peak in which season? (barplot grouped by season)

a = df.groupby(['Season','Category']).size()
a = a.reset_index(name = 'Count')
peak_cat = a.groupby('Season')['Count'].sum()
sns.barplot(x = a['Season'],y = a['Count'],hue = a['Category'],edgecolor = 'black')
plt.title('Peak product by season',fontweight = 'bold')
plt.ylabel('Products')

plt.show()

"""🔹 D. Subscription & Discount Analysis"""

# Do subscribed customers spend more than non-subscribed customers?

spend_money = df.groupby('Subscription Status')['Purchase Amount (USD)'].sum()
plt.bar(spend_money.index,spend_money.values,edgecolor = 'black',color = 'teal')
plt.title('Subscribed customers spend more than non-subscribed customers',fontweight = 'bold')
plt.xlabel('Yes or No')
plt.ylabel('Spending amount')

plt.show()

# # What percentage of subscribed users apply Discounts?


subscribed = df[df['Subscription Status'] == 'Yes']
subscribed_count = len(subscribed)


subscribed_discount = subscribed[subscribed['Discount Applied'] == 'Yes']
subscribed_discount_count = len(subscribed_discount)


percentage = round(subscribed_discount_count / subscribed_count * 100, 2)

print(f"{percentage}% of subscribed users apply discounts.")

# Does applying a Discount reduce the Review Rating?

discount_rate = df.groupby('Subscription Status')['Review Rating'].mean().round(2)
plt.bar(discount_rate.index,discount_rate.values,edgecolor = 'black')
plt.title('Discount reduce the Review Rating')
plt.xlabel('Discount')
plt.ylabel('Rating')
for i , v in enumerate(discount_rate):
  plt.text(i,v+0.05,str(v),ha = 'center')

plt.show()

"""🔹 E. Payment Method Insights"""

# Which Payment Method is used the most?

payment_method = df['Payment Method'].value_counts()
plt.bar(payment_method.index,payment_method.values,edgecolor = 'black')
plt.title('Most payment method used',fontweight = 'bold')
plt.xlabel('Payment Method')
plt.ylabel('Count')

for i , v in enumerate(payment_method):
  plt.text(i,v+5,str(v),ha= 'center')
plt.show()

# Which payment method results in highest purchase amount?

high_purchase = df.groupby('Payment Method')['Purchase Amount (USD)'].sum()
plt.bar(high_purchase.index,high_purchase.values,edgecolor = 'black')
plt.title('Payment method results in highest purchase amount',fontweight = 'bold')
plt.xlabel('Payment Method')
plt.ylabel('Purchase Amount')

for i , v in enumerate(high_purchase):
  plt.text(i,v+5,str(v),ha= 'center')
plt.show()

# Plot Review Rating by Payment Method.

payment_method_review = df.groupby('Payment Method')['Review Rating'].mean().round(2)
plt.bar(payment_method_review.index,payment_method_review.values,color = 'teal',edgecolor = 'black')
plt.title('Review Rating by Payment Method',fontweight = 'bold')
plt.xlabel('Payment Method')
plt.ylabel('Review Rating')

for i , v in enumerate(payment_method_review):
  plt.text(i,v+0.05,str(v),ha= 'center')
plt.show()

# Check if customers who use Credit Card/Cash have different spending patterns.

avg_spend = df.groupby('Payment Method')['Purchase Amount (USD)'].mean().round(2)
plt.bar(avg_spend.index, avg_spend.values, color=['crimson','steelblue','orange'])
plt.xlabel("Payment Method")
plt.ylabel("Average Purchase Amount (USD)")
plt.title("Spending Pattern by Payment Method", fontweight='bold')

for i, v in enumerate(avg_spend.values):
    plt.text(i, v + 1, str(v), ha='center')

plt.show()